name: asset_icon
description: "a powerful and customizable Flutter package for rendering asset-based icons with ease"
version: 1.0.0
homepage: https://github.com/hesham04Dev/localization_lite

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

