name: asset_icon
description: "A powerful and customizable Flutter package for rendering asset-based icons with ease"
version: 1.0.1
homepage: https://github.com/hesham04Dev/asset_icon

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.11
  args: ^2.6.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

